export const GET_CHARACTERS = 'GET_CHARACTERS';
export const ADD_CHARACTER = 'ADD_CHARACTER';
export const DELETE_CHARACTER = 'DELETE_CHARACTER';
export const CHARACTERS_LOADING = 'CHARACTERS_LOADING';